// panier.js — présentation du panier uniquement.
// Aucun calcul, aucune sélection, aucun nouveau run.
const CLE_PANIER = "archetype_panier";
function chargePanier(){try{const brut=localStorage.getItem(CLE_PANIER);if(!brut)return[];const panier=JSON.parse(brut);return Array.isArray(panier)?panier:[]}catch{return[]}}
function sauvePanier(liste){localStorage.setItem(CLE_PANIER,JSON.stringify(liste))}
function identitePanier(m){if(m&&m.match_id!==undefined&&m.match_id!==null&&String(m.match_id).trim()!=="")return `id:${String(m.match_id)}`;return `match:${String(m?.date||"").trim()}|${String(m?.heure_cameroun||m?.heure||"").trim()}|${String(m?.domicile||"").trim().toLowerCase()}|${String(m?.exterieur||"").trim().toLowerCase()}`}
function panierUnique(liste){const vu=new Set();return (liste||[]).filter(m=>{const cle=identitePanier(m);if(vu.has(cle))return false;vu.add(cle);return true})}
function retirerDuPanier(matchId){sauvePanier(chargePanier().filter(m=>String(m.match_id)!==String(matchId)));affichePanier()}
function ouvreAnalyse(conteneur){const details=conteneur.querySelector(".details-analyse");if(details){details.open=true;details.scrollIntoView({behavior:"smooth",block:"center"])}}
function construitCartePanier(item,signal){const conteneur=document.createElement("div");conteneur.className="carte-panier";const barre=document.createElement("div");barre.className="barre-panier";const boutonAnalyse=document.createElement("button");boutonAnalyse.className="bouton-analyse-panier";boutonAnalyse.type="button";boutonAnalyse.textContent="Voir l’analyse";boutonAnalyse.disabled=!(signal&&estArchetypeGo(signal));boutonAnalyse.addEventListener("click",()=>ouvreAnalyse(conteneur));barre.appendChild(boutonAnalyse);const boutonRetirer=document.createElement("button");boutonRetirer.className="bouton-retirer-panier";boutonRetirer.type="button";boutonRetirer.textContent="Retirer";boutonRetirer.addEventListener("click",()=>retirerDuPanier(item.match_id));barre.appendChild(boutonRetirer);conteneur.appendChild(barre);if(signal&&estArchetypeGo(signal))conteneur.appendChild(construitCarte(signal));else{const vide=document.createElement("div");vide.className="etat-vide";vide.innerHTML=`<strong>${echappeHtml(item.domicile||"Équipe à domicile")} – ${echappeHtml(item.exterieur||"Équipe à l'extérieur")}</strong><p>Aucune sélection Archetype pour ce match pour l'instant.</p>`;conteneur.appendChild(vide)}return conteneur}
function affichePanier(){const root=document.getElementById("panier-cartes"),statut=document.getElementById("statut-panier"),panier=panierUnique(chargePanier());if(!panier.length){statut.textContent="Ton panier est vide.";root.innerHTML="";return}sauvePanier(panier);statut.textContent="Chargement…";fetch(`precalcul_leger.json?_=${Date.now()}`).then(r=>{if(!r.ok)throw new Error(`precalcul_leger.json introuvable (${r.status})`);return r.json()}).then(d=>{const signaux=regroupeMatchs(d.signaux||[]);const parId=new Map(signaux.map(s=>[String(s.match_id),s]));root.innerHTML="";let nbAvecSelection=0;panier.forEach(item=>{const signal=parId.get(String(item.match_id));if(signal&&estArchetypeGo(signal))nbAvecSelection++;root.appendChild(construitCartePanier(item,signal))});statut.textContent=`${panier.length} match${panier.length>1?"s":""} dans le panier — ${nbAvecSelection} avec une sélection Archetype.`}).catch(e=>{statut.textContent="Erreur de chargement : "+e.message;console.error(e)})}
affichePanier();
